language: go
go:
  - tip
install:
  - go get -t github.com/genofire/hs_master-kss-monolith/...
  - go get github.com/mattn/goveralls
  - go get "golang.org/x/tools/cmd/cover"
script:
  - ./.test-coverage travis-ci
  - go install github.com/genofire/hs_master-kss-monolith/cmd/stock
